### ISSUE TITLE
Paramiko re-key fails

### ISSUE THREAD

**Issue by agraubert** [broadinstitute/canine#13]
See paramiko/paramiko#822

```
Exception: Key-exchange timed out waiting for key negotiation
Traceback (most recent call last):
  File "/home/sanand/.conda/envs/scrna/lib/python3.7/site-packages/paramiko/transport.py", line 2088, in run
    self._channel_handler_table[ptype](chan, m)
  File "/home/sanand/.conda/envs/scrna/lib/python3.7/site-packages/paramiko/channel.py", line 1187, in _handle_close
    self.transport._send_user_message(m)
  File "/home/sanand/.conda/envs/scrna/lib/python3.7/site-packages/paramiko/transport.py", line 1860, in _send_user_message
    "Key-exchange timed out waiting for key negotiation"
paramiko.ssh_exception.SSHException: Key-exchange timed out waiting for key negotiation
```

Must either decrease the re-key frequency to avoid ever re-keying or simply catch the error and refresh the client. Probably both

**Comment by agraubert** [comment]
Workaround is sufficient for now. Will keep pestering paramiko until maybe they fix the issue
